FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app
COPY ./ServiceB/*.csproj ./
COPY ./JaegerWrapper/ /JaegerWrapper/
RUN dotnet restore
COPY ./ServiceB ./
RUN dotnet publish -c Release -o out


FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/out/ .
COPY --from=build-env /app/appsettings.json .
ENTRYPOINT ["dotnet", "ServiceB.dll"]