FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app
COPY ./ServiceA/*.csproj ./
COPY ./JaegerWrapper/ /JaegerWrapper/
RUN dotnet restore
COPY ./ServiceA ./
RUN dotnet publish -c Release -o out


FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/out/ .
COPY --from=build-env /app/appsettings.json .
ENTRYPOINT ["dotnet", "ServiceA.dll"]